package com.example.visuallithuanian


//Red Fox = Raudona lapė
//Wolf = Vilkas
//Squirrel = Voverė
//Moose = Briedis
//Beaver = Bebras
//Bison = bizonų
//Frog = Varlė
//Cat = Katė
//Dog = šuo
//Wild Boar = Šernas
//Polar Bear = Baltoji meška
//Bear = Meška
//White Stork = Baltasis gandrovas
//Common Crane = pūkuotasis gandras
//Black Grouse = juodasis tetervinas
//Great Tit = didysis zylė
//Common Chaffinch = paprastasis žvirblis
//Eurasian Jay = eurazinis žvirblis
//Robin = raudonasis zylė
//Blackbird = juodasis varnėnas
//Buzzard = sklandytuvas
//Gray = Pilka
//Purple = Violetinė
//Europe = Europa
//Asia = Azija
//Africa = Afrika
//North America = Šiaurės Amerika
//South America = Pietų Amerika
//Australia = Australija
//Antarctica = Antarktida
//North = Šiaurės
//South = Pietų
//West = Vakarų
//East = Rytų
//North West = Šiaurės vakarai
//North East = Šiaurės rytai
//South West = Pietvakariai
//South East = Pietryčiai
//Rose = Rožė
//Daffodil = Narcizai
//Sunflower = Saulėgrąžos
//Peony = Bijūnas
//Tulip = Tulpė
//Daisy = Ramunė
//Raspberries = Avietės
//GooseBerry = Agrastas
//Plum = Slyvos
//Banana = Bananas
//Black currant = Juodieji serbentai
//Mango = Mango
//Zoo = Zoo
//Park = Parkas
//School = Mokykla
//Supermarket = Prekybos centras
//Resort = Kurortas
//Aquarium = Akvariumas
//Gymnasium = Sporto salė
//Pub = Pubas
//Please slow down = Prašau lėčiau.
//In cash = grynais
//Is there a good restaurant nearby? = Ar netoli yra geras restoranas?
//Nice to meet you = Malonu tave matyti
//coins = monetų
//airport = oro uostas
//Where is the ATM? = Kur yra bankomatas?
//Do you know where ... is? = Ar žinote, kur yra ...?
//train station = traukinių stotis
//at the police station = policijos nuovadoje
//single room = vienvietis kambarys
//passport = pasas
//Where is the toilet? = Kur yra tualetas?
//Reception = Registratūra
//How do I get to ....? = Kaip man nusigauti į ....?
//Thank you = Ačiū
//Delicious = Skanaus.
//My name is = Mano vardas yra
//boarding pass = įlaipinimo bilietas
//Do you speak English? = Ar tu kalbi angliškai?
//bank note = banko kupiūra
//exit = išėjimas
//Nice to meet you = Malonu susipažinti
//I do not speak english. = Aš nemoku anglų kalbos.
//When does the bus leave? = Kada išvyksta autobusas?
//How are you? = Kaip laikaisi?
//How to say.... = Kaip sakyti....
//Can you call a taxi? = Ar galite išsikviesti taksi?
//map = Žemėlapis
//I am allergic to nuts. = Esu alergiška riešutams.
//I don't know = Nežinau
//barter shop = mainų parduotuvė
//bus station = autobusų stotis
//Can I borrow ...? = Ar galiu pasiskolinti ...?
//When does breakfast start? = Kada prasideda pusryčiai?
//I'm sorry = Atsiprašau
//Enjoy your stay. = Mėgaukitės viešnage.
//Can I get your ID card? = Ar galiu gauti jūsų asmens tapatybės kortelę?
//Accountant = Buhalteris
//Architect = Architektas
//Chef = Šefas
//Nurse = Slaugytojas
//Musician = Muzikantas
//Autumn = Ruduo
//Winter = Žiema
//Meteor = Meteoras
//Comet = Kometa
//Mercury = Merkurijus
//Venus = Venera
//Earth = Žemė
//Mars = Marsas
//Jupiter = Jupiteris
//Saturn = Saturnas
//Uranus = Uranas
//Moon = Mėnulis
//Planets = Planetos
//Football = Futbolas
//Ice Hockey = Ledo ritulys
//Chess = Šachmatai
//Cycling = Dviračių sportas
//Swimming = Plaukimas
//Rugby = Regbis
//Skating = Slidinėjimas
//Month = Mėnuo
//Decade = Dešimtmetis
//Century = Amžius
//Millennium = Tūkstantmetis
//Second = Sekundė
//Minute = Minutė
//Bus = Autobusas
//Car = Automobilis
//Train = Traukinys
//Bicycle = Dviratis
//Motorcycle = Motociklas
//Boat = Valtis
//Airplane = Lėktuvas
//Helicopter = Sraigtasparnis
//Truck = Sunkvežimis
//Taxi = Taksi




