package com.example.visuallithuanian
//

//"to get/receive gets got what?" = "gauti gauna gavo ką?"
//"email" = "elektroninis laiškas"
//"sign signs signed what?" = "pasirašyti pasirašo pasirašė ką?"
//"Signature" = "parašas"
//"Contract" = "sutartis"
//"to wait waits waited for what?" = "palaukti palaukia palaukė ko?"
//"to ask asks asked" = "paklausti paklausia paklausė"
//"to call calls called who?" = "paskambinti paskambina paskambino kam?"
//"paper" = "popierius"
//"sheet of paper" = "popieriaus lapas"
//
//"computer" = "kompiuteris"
//"printer" = "spausdintuvas"



//"work" = "darbas"
//"rest day / public holiday" = "poilsio / nedarbo diena"
//"Workplace" = "darbovietė"
//"firm/company" = "įmonė"
//"director / manager / CEO" = "direktorus / direktorė"
//"colleague" = "kolega / kolegė"
//"employee" = "darbuotojas / darbotoja"
//"client / customer" = "klientas / klientė"
//"busy" = "užsiemęs (m) / užsiemusi (f)"
//"business trip" = "komandiruotė"
//
//"meeting" = "susirinkimas/susitinkimas"
//"cabinet" = "kabinetas"
//"to begin begins began" = "prasidėti prasideda prasidėjo"
//"to finish/to come to an end finishes finished" = "pasibaigti pasibaiga pasibaigė"
//"to start starts started what?" = "pradėti pradeda pradėjo ką?"
//"to finish finishes finished what?" = "baigti baigia baigė ką?"
//"to finish work" = "baigti darbą"
//"lunch break" = "pietų pertrauka"
//"to have vacation vacationing vacationed" = "atostogauti atostogauja atostogavo"

//"holidays vacation" = "atostogos"
//"to print prints printed what?" = "išspausdinti išspausdina išspausdino ką?"
//"Document" = "dokumentas"
//"copy" = "kopija"
//"to inform informs informed what? who?" = "perduoti perduoda perdavė ką? kam?"
//"to give/hand gives/hands gave what? to whom?" = "paduoti paduoda padavė ką? kam?"
//"to say says said what? to whom?" = "pasakyti pasako pasakė ką? kam?"
//"to take takes took what? to whom?" = "nunešti nuneša nunešė ką? kam?"
//"to write writes wrote what? to whom?" = "rašyti rašo raše ką? kam?"
//"to send sends sent what?" = "išsiųsti išsiunčia išsiunte ką?"

// Food and Ingerdients
//"egg" = "kiaušinis"
//"kiwi" = "kivis"
//"Blue cheese" = "Mėlynasis sūris"
//"coffee" = "kava"
//"blueberries" = "mėlynių"
//"bacon" = "lašiniai"
//"breakfast" = "pusryčiai"
//"peach" = "persikas"
//"forest honey" = "miško medus"
//"pepper" = "pipirai"
//
//"lunch" = "pietūs"
//"fish" = "žuvis"
//"raspberry" = "avietė"
//"vegetables" = "daržovės"
//"fruit" = "vaisius"
//"garlic" = "česnakas"
//"Chocolate" = "Šokoladas"
//"sparkling water" = "gazuotas vanduo"
//"mushroom" = "pievagrybis"
//"steak" = "kepsnys"  ///given to record
//
//"snack" = "užkandis"
//"sausage" = "dešra"
//"pear" = "kriaušė"
//"still water" = "Negazuotas vanduo"
//"Watermelon" = "arbūzas"
//"Salad" = "salotos"
//"Carrot" = "morką"
//"Ham" = "kumpis"
//"Beef" = "jautiena"
//"Potato" = "bulvė"
//
//"crumbs" = "dribsniai"
//"Apples" = "obuolių"
//"marmalade" = "marmeladas"
//"Pineapple" = "ananasas"
//"Tea" = "arbata"
//"Bread" = "duona"
//"cheese" = "sūris"
//"yogurt" = "jogurtas"
//"salt" = "druska"
//"butter" = "sviestas"
//
//"Strawberry" = "Braškė"
//"Orange" = "apelsinas"
//"lime" = "kalkės"
//"lemon" = "citrina"
//"mustard" = "garstyčios"
//"avocado" = "avokadas"
//"Onion" = "svogūnas"
//"mushroom" = "grybas"
//"cherry" = "vyšnia"
//"cauliflower" = "žiediniai kopūstai"
//
//"salami" = "saliamis"
//"juice" = "sultys"
//"Pasta" = "Makaronai"
//"Chicken" = "vištiena"
//"Sauce" = "padažas"
//"grapes" = "vynuoges"
//"pork" = "kiauliena"
//"rice" = "ryžiai"
//"spaghetti" = "spagečiai"
//"broccoli" = "brokoliai"
//
//"milk" = "pienas"
//"wine" = "vynas"
//"meat" = "mėsa"

//"to clean" = "valyti"
//"smoking" = "rūkyti"
//"to wait" = "palaukti"
//"to ride" = "važiuoti"
//"enter" = "įveskite"
//"to put" = "įdėti"
//"to meet" = "susitikti"
//"take it" = "imk"
//"to fly" = "skristi"
//"Close" = "Uždaryti"
//
//"to live" = "gyventi"
//"say" = "sakyk"
//"to stay" = "pasilikti"
//"to save" = "sutaupyti"
//"to swim" = "plaukti"
//"to run" = "bėgti"
//"to try" = "bandyti"
//"to do" = "padaryti"
//"boiled" = "virti"
//"to create" = "sukurti"
//"to invite" = "pakviesti"
//"to hear" = "girdėti"
//"see" = "matyti"
//"turn" = "posūkis"
//"allow" = "leisti"
//"prepared" = "paruošti"
//"to finish" = "baigti"
//"to lose" = "prarasti"
//"to educate" = "šviesti"
//"to sit" = "sėdėti"

// Celebrations-Holidays

//"celebration" = "švente"
//"to celebrate celebrates celebrated what?" = "švęsti švenčia šventė ką?"
//"birthday" = "gimtadienis"
//"name day" = "vardadienis"
//"anniversary" = "jubiliejus"
//"to invite invites invited what?" = "kviesti kviečia kviektė ką?"
//"party" = "vakarėlis"
//"guest" = "svečias"
//"to go visit (as a guest)" = "eiti į svečius"
//"to invite guests" = "kviesti į svečius"
//
//"to be a guest" = "būti svečiuose"
//"to give" = "dovanoti"
//"to get gets got what?" = "gauti gauna gavo ką?"
//"gift" = "dovana"
//"flower" = "gėlė"
//"Postcard" = "atvirukas"
//"to send" = "išsiųsti"
//"to write writes wrote postcard" = "užrašyti užrašo užrašė atvirukas"
//"cake" = "tortas"
//"candles" = "žvakutė"
//"Christmas Eve" = "Kūčios"
//
//"to congratulate" = "sveikinti"
//"to wish" = "linkėti"
//"Christmas" = "Kalėdos"
//"christmas tree" = "eglutė"
//"Santa Claus" = "Kalėdų senelis"
//"candle" = "žvakė"
//"New Year" = "Naujieji Metai"
//"to wait" = "sutikti"
//"fireworks" = "fejerverkai"
//"Easter" = "Velykos"
//
//"Easter egg" = "margutis"
//"to dye" = "dažyti"
//"public holidays" = "valstybinės šventes"
//"flag" = "vėliava"
//"success" = "sėkme"
//"happiness" = "laimė"
//"Joy" = "džiaugsmas"
//"happy" = "laimingas"
//"beloved" = "mylimas"
//"honourable" = "gerbiamas"
//"colourful" = "spalvingas"
//"Popular" = "popularus"



//Sports Flashcards

//"final" = "galutinis"
//"pool" = "baseinas"
//"champion" = "čempionas"
//"Quarterly" = "ketvirtis"
//"injured" = "susižeisti"
//"field" = "laukas"
//"player" = "žaidėjas"
//"decathlon competition" = "dešimtkovės varžybos"
//"darts" = "smiginis"
//"whistle" = "švilpti"
//"Winner" = "Nugalėtojas"
//"to get along" = "kad susitvarkytų"
//"captain" = "kapitonas"
//"slide" = "čiuožykla"
//"yoga" = "joga"
//"team" = "komanda"
//"baseball" = "beisbolas"
//"to play sports" = "Sportuoti"
//"to overcome" = "įveikti"
//"judge" = "teisėjas"
//"triathlon" = "triatlonas"
//"to win" = "laimėti"
//"basketball" = "krepšinį"
//"trainer" = "treneris"
//"exercise" = "pratimas"
//"quarterfinals" = "ketvirtfinalis"
//"viewer" = "žiūrovas"
//"trophy" = "trofėjus"
//"world Championship" = "pasaulio čempionatas"
//"sports equipment" = "sporto įranga"
//"game" = "žaidimas"
//"fitness gym" = "treniruoklių salė"
//"stadium" = "stadionas"
//"manual" = "rankinis"
//"aerobics" = "aerobika"
//"weightlifting" = "sunkiosios atletikos"
//"injury" = "sužalojimas"
//"skis" = "slidės"
//"badminton" = "badmintonas"
//"gym" = "sporto salė"
//"tennis court" = "teniso kortas"


//Number Fragment
//"a thousand = "tūkstantis"
//"ten = "dešimt"
//"ten thousand = "dešimt tukstancių"
//"one hundred = "šimtas"
//"one hundred thousand = "šimtas tūkstančių"
//"million = "milijonas"
//"the first train = "pirmasis traukinis"
//"two tickets = "du bilietai"
//"the last train = "paskutinis traukinis"
//"first aid = "pirmosios pagalbos"



// Things Flashcard

//"clothes" = "drabužiai"
//"shirt" = "marškiniai"
//"to put on" = "apsivilkti"
//"to take off (clothes)" = "nusivilkti"
//"short sleeves" = "trumpos rankovės"
//"trousers" = "kelnės"
//"skirt" = "sijonas"
//"a dress" = "suknelė"
//"a white coat" = "baltas paltas"
//"jeans" = "džinsai"
//
//"a ring" = "žiedas"
//"sun glasses" = "saulės akiniai"
//"scarf" = "skara"
//"a handbag" = "rankinukas"
//"Gold" = "auksas"
//"weight" = "svoris"
//"capacity" = "talpa"
//"dimensions (dimension)" = "matmenys (matmuo)"
//"shoes" = "batai"
//"sandals" = "sandalai"
//"oil and gas" = "nafta ir dujos"
//"guitar" = "gitara"
//"piano" = "pianinas"
//"violin" = "smuikas"
//"letter" = "laiškas"
//"Envelope" = "vokas"
//"Postcard" = "atvirukas"
//"Package" = "paketas"
//"picture/image" = "nuotrauka"
//"drugs" = "vaistai"
//"tavo dovana" = "tavo dovana"

