package com.example.visuallithuanian
//

//"to get/receive gets got what?" = "gauti gauna gavo ką?"
//"email" = "elektroninis laiškas"
//"sign signs signed what?" = "pasirašyti pasirašo pasirašė ką?"
//"Signature" = "parašas"
//"Contract" = "sutartis"
//"to wait waits waited for what?" = "palaukti palaukia palaukė ko?"
//"to ask asks asked" = "paklausti paklausia paklausė"
//"to call calls called who?" = "paskambinti paskambina paskambino kam?"
//"paper" = "popierius"
//"sheet of paper" = "popieriaus lapas"
//
//"computer" = "kompiuteris"
//"printer" = "spausdintuvas"



//"work" = "darbas"
//"rest day / public holiday" = "poilsio / nedarbo diena"
//"Workplace" = "darbovietė"
//"firm/company" = "įmonė"
//"director / manager / CEO" = "direktorus / direktorė"
//"colleague" = "kolega / kolegė"
//"employee" = "darbuotojas / darbotoja"
//"client / customer" = "klientas / klientė"
//"busy" = "užsiemęs (m / užsiemusi (f"
//"business trip" = "komandiruotė"
//
//"meeting" = "susirinkimas/susitinkimas"
//"cabinet" = "kabinetas"
//"to begin begins began" = "prasidėti prasideda prasidėjo"
//"to finish/to come to an end finishes finished" = "pasibaigti pasibaiga pasibaigė"
//"to start starts started what?" = "pradėti pradeda pradėjo ką?"
//"to finish finishes finished what?" = "baigti baigia baigė ką?"
//"to finish work" = "baigti darbą"
//"lunch break" = "pietų pertrauka"
//"to have vacation vacationing vacationed" = "atostogauti atostogauja atostogavo"

//"holidays vacation" = "atostogos"
//"to print prints printed what?" = "išspausdinti išspausdina išspausdino ką?"
//"Document" = "dokumentas"
//"copy" = "kopija"
//"to inform informs informed what? who?" = "perduoti perduoda perdavė ką? kam?"
//"to give/hand gives/hands gave what? to whom?" = "paduoti paduoda padavė ką? kam?"
//"to say says said what? to whom?" = "pasakyti pasako pasakė ką? kam?"
//"to take takes took what? to whom?" = "nunešti nuneša nunešė ką? kam?"
//"to write writes wrote what? to whom?" = "rašyti rašo raše ką? kam?"
//"to send sends sent what?" = "išsiųsti išsiunčia išsiunte ką?"

// Food and Ingerdients
//"egg" = "kiaušinis"
//"kiwi" = "kivis"
//"Blue cheese" = "Mėlynasis sūris"
//"coffee" = "kava"
//"blueberries" = "mėlynių"
//"bacon" = "lašiniai"
//"breakfast" = "pusryčiai"
//"peach" = "persikas"
//"forest honey" = "miško medus"
//"pepper" = "pipirai"
//
//"lunch" = "pietūs"
//"fish" = "žuvis"
//"raspberry" = "avietė"
//"vegetables" = "daržovės"
//"fruit" = "vaisius"
//"garlic" = "česnakas"
//"Chocolate" = "Šokoladas"
//"sparkling water" = "gazuotas vanduo"
//"mushroom" = "pievagrybis"



//"steak" = "kepsnys"  ///given to record
//
//"snack" = "užkandis"
//"sausage" = "dešra"
//"pear" = "kriaušė"
//"still water" = "Negazuotas vanduo"
//"Watermelon" = "arbūzas"
//"Salad" = "salotos"
//"Carrot" = "morką"
//"Ham" = "kumpis"
//"Beef" = "jautiena"
//"Potato" = "bulvė"
//
//"crumbs" = "dribsniai"
//"Apples" = "obuolių"
//"marmalade" = "marmeladas"
//"Pineapple" = "ananasas"
//"Tea" = "arbata"
//"Bread" = "duona"
//"cheese" = "sūris"
//"yogurt" = "jogurtas"
//"salt" = "druska"
//"butter" = "sviestas"
//
//"Strawberry" = "Braškė"
//"Orange" = "apelsinas"
//"lime" = "kalkės"
//"lemon" = "citrina"
//"mustard" = "garstyčios"
//"avocado" = "avokadas"
//"Onion" = "svogūnas"
//"mushroom" = "grybas"
//"cherry" = "vyšnia"
//"cauliflower" = "žiediniai kopūstai"
//
//"salami" = "saliamis"
//"juice" = "sultys"
//"Pasta" = "Makaronai"
//"Chicken" = "vištiena"
//"Sauce" = "padažas"
//"grapes" = "vynuoges"
//"pork" = "kiauliena"
//"rice" = "ryžiai"
//"spaghetti" = "spagečiai"
//"broccoli" = "brokoliai"
//
//"milk" = "pienas"
//"wine" = "vynas"
//"meat" = "mėsa"

//"to clean" = "valyti"
//"smoking" = "rūkyti"
//"to wait" = "palaukti"
//"to ride" = "važiuoti"
//"enter" = "įveskite"
//"to put" = "įdėti"
//"to meet" = "susitikti"
//"take it" = "imk"
//"to fly" = "skristi"
//"Close" = "Uždaryti"
//
//"to live" = "gyventi"
//"say" = "sakyk"
//"to stay" = "pasilikti"
//"to save" = "sutaupyti"
//"to swim" = "plaukti"
//"to run" = "bėgti"
//"to try" = "bandyti"
//"to do" = "padaryti"
//"boiled" = "virti"
//"to create" = "sukurti"
//"to invite" = "pakviesti"
//"to hear" = "girdėti"
//"see" = "matyti"
//"turn" = "posūkis"
//"allow" = "leisti"
//"prepared" = "paruošti"
//"to finish" = "baigti"
//"to lose" = "prarasti"
//"to educate" = "šviesti"
//"to sit" = "sėdėti"


// Things Flashcard

//"clothes" = "drabužiai"
//"shirt" = "marškiniai"
//"to put on" = "apsivilkti"
//"to take off (clothes" = "nusivilkti"
//"short sleeves" = "trumpos rankovės"
//"trousers" = "kelnės"
//"skirt" = "sijonas"
//"a dress" = "suknelė"
//"a white coat" = "baltas paltas"
//"jeans" = "džinsai"

//"a ring" = "žiedas"
//"sun glasses" = "saulės akiniai"
//"scarf" = "skara"
//"a handbag" = "rankinukas"
//"Gold" = "auksas"
//"weight" = "svoris"
//"capacity" = "talpa"
//"dimensions" = "matmenys"
//"shoes" = "batai"
//"sandals" = "sandalai"
//"oil and gas" = "nafta ir dujos"
//"guitar" = "gitara"
//"piano" = "pianinas"
//"violin" = "smuikas"
//"letter" = "laiškas"
//"Envelope" = "vokas"
//"Postcard" = "atvirukas"
//"Package" = "paketas"
//"picture/image" = "nuotrauka"
//"drugs" = "vaistai"
//"tavo dovana" = "tavo dovana"


