package com.example.visuallithuanian.constants

import com.example.visuallithuanian.R

object BestWords100Singleton {

    val hashMapbestwords = HashMap<String, Triple<String, Int, Int>>()

    init {
        // Hashmap of strings that will shown on cardview front and back side

        hashMapbestwords["immediately"] = Triple("nedelsiant", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["in addition"] = Triple("papildomai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["finally"] = Triple("galiausiai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["worm"] = Triple("kirminas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["area"] = Triple("plotas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["deer"] = Triple("elnias", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["camel"] = Triple("kupranugaris", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["By the way"] = Triple("be to", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["cough"] = Triple("kosulys", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["experience"] = Triple("patirtis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["account"] = Triple("paskyra", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["every year"] = Triple("kasmet", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["regret it"] = Triple("gailėtis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["direction"] = Triple("kryptis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["overall"] = Triple("apskritai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["inclination"] = Triple("polinkis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["edge"] = Triple("kraštas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["chalk"] = Triple("kreida", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["punishment"] = Triple("bausmė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["voice"] = Triple("balsas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["approval"] = Triple("patvirtinimo", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["main"] = Triple("pagrindinis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["exchange"] = Triple("mainai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["behavior"] = Triple("elgesį", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["to doubt something"] = Triple("abejoti kažkuo", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Last but not least"] = Triple("Paskutinis, bet ne prasčiausias", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["sneeze"] = Triple("čiaudėti", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["butterfly"] = Triple("drugelis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["insurance"] = Triple("draudimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["by accident"] = Triple("atsitiktinai", R.drawable.computer1, R.raw.computer)


        hashMapbestwords["nose"] = Triple("triukšmas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["transport"] = Triple("transportas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Shop"] = Triple("Parduotuvė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["isolated"] = Triple("izoliuotas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["able"] = Triple("sugeba", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Cover"] = Triple("Uždengti", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["advertising"] = Triple("reklama", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["owner"] = Triple("savininkas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["is overwhelmed"] = Triple("perpildytas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Distance"] = Triple("Atstumas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["current"] = Triple("srovė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["kenkki"] = Triple("kenkti", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["certain"] = Triple("tam tikras", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["in this case"] = Triple("tokiu atveju", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["mark"] = Triple("ženklas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["hospital"] = Triple("ligoninė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["result"] = Triple("rezultatas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Religion"] = Triple("Religija", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["mosque"] = Triple("mečetę", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["statue"] = Triple("statula", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["regularly"] = Triple("reguliariai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["value"] = Triple("vertė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["purpose"] = Triple("tikslas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["hole"] = Triple("skylė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["castle"] = Triple("pilis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["But"] = Triple("Tačiau", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["especially"] = Triple("ypač", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["knowledge"] = Triple("žinių", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["rarely"] = Triple("retai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["event"] = Triple("renginys", R.drawable.computer1, R.raw.computer)

        hashMapbestwords["surprise"] = Triple("staigmena", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["The church"] = Triple("Bažnyčia", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["always"] = Triple("visada", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["suddenly"] = Triple("staiga", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["solution"] = Triple("sprendimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["most importantly"] = Triple("svarbiausia", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["beetle"] = Triple("vabalas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["asparagus"] = Triple("šparagai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Government"] = Triple("Vyriausybė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["kindergarten"] = Triple("darželis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["noisy"] = Triple("triukšminga", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["flight"] = Triple("skrydis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["reason"] = Triple("priežastis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["at school"] = Triple("mokykloje", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["road"] = Triple("kelias", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["seagull"] = Triple("žuvėdra", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["in short"] = Triple("trumpai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["decrease"] = Triple("sumažėjimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["really"] = Triple("tikrai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["exactly"] = Triple("tiksliai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["research"] = Triple("tyrimus", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Sheep"] = Triple("avių", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["it seems"] = Triple("atrodo", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["officially"] = Triple("oficialiai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["argument"] = Triple("argumentas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["industry"] = Triple("pramonės", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["request"] = Triple("prašymą", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["in line"] = Triple("eilėje", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["test"] = Triple("bandymas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["opinion"] = Triple("nuomonę", R.drawable.computer1, R.raw.computer)

        hashMapbestwords["league"] = Triple("liga", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["with caution"] = Triple("atsargiai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["increase"] = Triple("padidinti", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["often"] = Triple("dažnai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["size"] = Triple("dydis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["naturally"] = Triple("natūraliai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["authority"] = Triple("autoritetas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Help"] = Triple("Pagalba", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["payment"] = Triple("mokėjimą", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["concrete"] = Triple("betonas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["born"] = Triple("gimimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["on the other hand"] = Triple("iš kitos pusės", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["question"] = Triple("klausimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["space"] = Triple("kosmosas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["love"] = Triple("meilus", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["fast"] = Triple("greitai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["part"] = Triple("dalis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Every day"] = Triple("kasdien", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["there is no point"] = Triple("nėra prasmės", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["company"] = Triple("kompanija", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["actual"] = Triple("faktinis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["easily"] = Triple("lengvai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["heat"] = Triple("karštis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Food"] = Triple("Maistas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["journey"] = Triple("kelionė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Be quiet"] = Triple("Būti tyliam", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["accidentally"] = Triple("netyčia", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Proposal"] = Triple("Pasiūlymas", R.drawable.computer1, R.raw.computer)
    }
}