package com.example.visuallithuanian.constants

import com.example.visuallithuanian.R

object BestWords100Singleton {

    val hashMapbestwords = HashMap<String, Triple<String, Int, Int>>()

    init {
        // Hashmap of strings that will shown on cardview front and back side

        hashMapbestwords["immediately"] = Triple("nedelsiant", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["in addition"] = Triple("papildomai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["finally"] = Triple("galiausiai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["worm"] = Triple("kirminas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["area"] = Triple("plotas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["deer"] = Triple("elnias", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["camel"] = Triple("kupranugaris", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["By the way"] = Triple("be to", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["cough"] = Triple("kosulys", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["experience"] = Triple("patirtis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["account"] = Triple("paskyra", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["every year"] = Triple("kasmet", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["regret it"] = Triple("gailėtis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["direction"] = Triple("kryptis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["overall"] = Triple("apskritai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["inclination"] = Triple("polinkis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["edge"] = Triple("kraštas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["chalk"] = Triple("kreida", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["punishment"] = Triple("bausmė", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["voice"] = Triple("balsas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["approval"] = Triple("patvirtinimo", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["main"] = Triple("pagrindinis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["exchange"] = Triple("mainai", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["behavior"] = Triple("elgesį", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["to doubt something"] = Triple("abejoti kažkuo", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["Last but not least"] = Triple("Paskutinis, bet ne prasčiausias", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["sneeze"] = Triple("čiaudėti", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["butterfly"] = Triple("drugelis", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["insurance"] = Triple("draudimas", R.drawable.computer1, R.raw.computer)
        hashMapbestwords["by accident"] = Triple("atsitiktinai", R.drawable.computer1, R.raw.computer)


        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)

        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)

        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)
        hashMapbestwords[""] = Triple("", R.drawable.computer1, R.raw.computer)





    }
}