package com.example.visuallithuanian.constants

import com.example.visuallithuanian.R

object BestWords100Singleton {

    val hashMapbestwords = HashMap<String, Triple<String, Int, Int>>()

    init {
        // Hashmap of strings that will shown on cardview front and back side

        hashMapbestwords["immediately"] = Triple("nedelsiant", R.drawable.immediately, R.raw.immediately)
        hashMapbestwords["in addition"] = Triple("papildomai", R.drawable.inaddition, R.raw.inaddition)
        hashMapbestwords["finally"] = Triple("galiausiai", R.drawable.finally11, R.raw.finally1)
        hashMapbestwords["area"] = Triple("plotas", R.drawable.area, R.raw.area)
        hashMapbestwords["By the way"] = Triple("be to", R.drawable.emptyimage, R.raw.bytheway)
        hashMapbestwords["cough"] = Triple("kosulys", R.drawable.cough, R.raw.cough)
        hashMapbestwords["experience"] = Triple("patirtis", R.drawable.experience, R.raw.experience)
        hashMapbestwords["account"] = Triple("paskyra", R.drawable.account, R.raw.account)
        hashMapbestwords["every year"] = Triple("kasmet", R.drawable.everyyear, R.raw.everyyear)
        hashMapbestwords["regret it"] = Triple("gailėtis", R.drawable.regret, R.raw.regretit)
        hashMapbestwords["direction"] = Triple("kryptis", R.drawable.direction, R.raw.direction)
        hashMapbestwords["overall"] = Triple("apskritai", R.drawable.overall, R.raw.overall)
        hashMapbestwords["inclination"] = Triple("polinkis", R.drawable.inclination, R.raw.inclination)
        hashMapbestwords["edge"] = Triple("kraštas", R.drawable.edge, R.raw.edge)
        hashMapbestwords["chalk"] = Triple("kreida", R.drawable.chalk, R.raw.chalk)
        hashMapbestwords["punishment"] = Triple("bausmė", R.drawable.punishment, R.raw.punishment)
        hashMapbestwords["voice"] = Triple("balsas", R.drawable.voice, R.raw.voice)
        hashMapbestwords["approval"] = Triple("patvirtinimas", R.drawable.approval, R.raw.approval)
        hashMapbestwords["main"] = Triple("pagrindinis", R.drawable.main, R.raw.main)
        hashMapbestwords["exchange"] = Triple("mainai", R.drawable.exchange, R.raw.exchange)
        hashMapbestwords["behavior"] = Triple("elgesys", R.drawable.behavior, R.raw.behaviour)
        hashMapbestwords["beetle"] = Triple("vabalas", R.drawable.bettle, R.raw.bettle)
        hashMapbestwords["Shop"] = Triple("Parduotuvė", R.drawable.shop, R.raw.shop)
        hashMapbestwords["butterfly"] = Triple("drugelis", R.drawable.butterfly, R.raw.butterfly)
        hashMapbestwords["hospital"] = Triple("ligoninė", R.drawable.hospital, R.raw.hospitak)
        hashMapbestwords["mosque"] = Triple("mečetę", R.drawable.mosque, R.raw.mosque)
        hashMapbestwords["The church"] = Triple("Bažnyčia", R.drawable.church, R.raw.thechurch)
        hashMapbestwords["kindergarten"] = Triple("darželis", R.drawable.kindergarten, R.raw.kindergarten)
        hashMapbestwords["castle"] = Triple("pilis", R.drawable.castle1, R.raw.castle)
        hashMapbestwords["noisy"] = Triple("triukšminga", R.drawable.noisy, R.raw.noisy)
        hashMapbestwords["flight"] = Triple("skrydis", R.drawable.flight, R.raw.flight)
        hashMapbestwords["reason"] = Triple("priežastis", R.drawable.reason, R.raw.reason)
        hashMapbestwords["at school"] = Triple("mokykloje", R.drawable.school, R.raw.primaryschool)
        hashMapbestwords["road"] = Triple("kelias", R.drawable.road, R.raw.road)
        hashMapbestwords["seagull"] = Triple("žuvėdra", R.drawable.seagull, R.raw.seagull)
        hashMapbestwords["worm"] = Triple("kirminas", R.drawable.worm, R.raw.worm)
        hashMapbestwords["deer"] = Triple("elnias", R.drawable.deer, R.raw.deer)
        hashMapbestwords["camel"] = Triple("kupranugaris", R.drawable.camel, R.raw.camel)
        hashMapbestwords["advertising"] = Triple("reklama", R.drawable.advertising, R.raw.advertising)
        hashMapbestwords["Sheep"] = Triple("avių", R.drawable.sheep, R.raw.sheep)
        hashMapbestwords["increase"] = Triple("padidinti", R.drawable.increase, R.raw.increase)


        hashMapbestwords["to doubt something"] = Triple("abejoti kažkuo", R.drawable.todoubtsomething, R.raw.todoubtsomething)
        hashMapbestwords["Last but not least"] = Triple("Paskutinis, bet ne prasčiausias", R.drawable.emptyimage, R.raw.lastbutnotleast)
        hashMapbestwords["sneeze"] = Triple("čiaudėti", R.drawable.sneeze, R.raw.sneeze)
        hashMapbestwords["insurance"] = Triple("draudimas", R.drawable.insurance, R.raw.insurance)
        hashMapbestwords["by accident"] = Triple("atsitiktinai", R.drawable.byaccident, R.raw.byaccident)
        hashMapbestwords["noise"] = Triple("triukšmas", R.drawable.noisy, R.raw.noise)
        hashMapbestwords["transport"] = Triple("transportas", R.drawable.transportation, R.raw.transport)
        hashMapbestwords["isolated"] = Triple("izoliuotas", R.drawable.isolated, R.raw.isolated)
        hashMapbestwords["able"] = Triple("sugeba", R.drawable.emptyimage, R.raw.able)
        hashMapbestwords["Cover"] = Triple("Uždengti", R.drawable.cover, R.raw.cover)
        hashMapbestwords["owner"] = Triple("savininkas", R.drawable.owner, R.raw.owner)
        hashMapbestwords["is overwhelmed"] = Triple("perpildytas", R.drawable.overwhelmed, R.raw.isoverwhelmed)
        hashMapbestwords["Distance"] = Triple("Atstumas", R.drawable.distance, R.raw.distance)
        hashMapbestwords["current"] = Triple("srovė", R.drawable.current, R.raw.current)
        hashMapbestwords["certain"] = Triple("tam tikras", R.drawable.emptyimage, R.raw.certain)
        hashMapbestwords["in this case"] = Triple("tokiu atveju", R.drawable.emptyimage, R.raw.inthiscase)
        hashMapbestwords["mark"] = Triple("ženklas", R.drawable.mark, R.raw.mark)
        hashMapbestwords["result"] = Triple("rezultatas", R.drawable.result1, R.raw.result)
        hashMapbestwords["Religion"] = Triple("Religija", R.drawable.religion1, R.raw.religion)
        hashMapbestwords["statue"] = Triple("statula", R.drawable.statue, R.raw.statue)
        hashMapbestwords["regularly"] = Triple("reguliariai", R.drawable.regularly, R.raw.regularly)
        hashMapbestwords["value"] = Triple("vertė", R.drawable.value, R.raw.value1)
        hashMapbestwords["purpose"] = Triple("tikslas", R.drawable.purpose1, R.raw.purpose)
        hashMapbestwords["hole"] = Triple("skylė", R.drawable.hole, R.raw.hole)
        hashMapbestwords["But"] = Triple("Tačiau", R.drawable.emptyimage, R.raw.but)
        hashMapbestwords["especially"] = Triple("ypač", R.drawable.emptyimage, R.raw.especially)
        hashMapbestwords["knowledge"] = Triple("žinios", R.drawable.knowledge, R.raw.knowledge)
        hashMapbestwords["rarely"] = Triple("retai", R.drawable.rare, R.raw.rarerly)
        hashMapbestwords["event"] = Triple("renginys", R.drawable.event1, R.raw.event)
        hashMapbestwords["surprise"] = Triple("staigmena", R.drawable.surprise1, R.raw.surprise)
        hashMapbestwords["always"] = Triple("visada", R.drawable.emptyimage, R.raw.always)
        hashMapbestwords["suddenly"] = Triple("staiga", R.drawable.emptyimage, R.raw.suddenly)
        hashMapbestwords["solution"] = Triple("sprendimas", R.drawable.solution, R.raw.solution)
        hashMapbestwords["most importantly"] = Triple("svarbiausia", R.drawable.importantly, R.raw.mostimportantly)
        hashMapbestwords["asparagus"] = Triple("šparagas", R.drawable.asparagus, R.raw.asparagus)
        hashMapbestwords["Government"] = Triple("Vyriausybė", R.drawable.government, R.raw.government)
        hashMapbestwords["in short"] = Triple("trumpai", R.drawable.emptyimage, R.raw.inshort)
        hashMapbestwords["decrease"] = Triple("sumažėjimas", R.drawable.decrease, R.raw.decrease)
        hashMapbestwords["really"] = Triple("tikrai", R.drawable.really, R.raw.really)
        hashMapbestwords["exactly"] = Triple("tiksliai", R.drawable.exactly1, R.raw.exactly)
        hashMapbestwords["research"] = Triple("tyrimas", R.drawable.research, R.raw.research)
        hashMapbestwords["it seems"] = Triple("atrodo", R.drawable.emptyimage, R.raw.itseems)
        hashMapbestwords["love"] = Triple("meilus", R.drawable.love, R.raw.love)

        hashMapbestwords["officially"] = Triple("oficialiai", R.drawable.officially, R.raw.officilaly)
        hashMapbestwords["argument"] = Triple("argumentas", R.drawable.arguement, R.raw.argument)
        hashMapbestwords["industry"] = Triple("industrija", R.drawable.industry, R.raw.industry)
        hashMapbestwords["request"] = Triple("prašymas", R.drawable.request, R.raw.request)
        hashMapbestwords["in line"] = Triple("eilėje", R.drawable.emptyimage, R.raw.inline1)
        hashMapbestwords["test"] = Triple("bandymas", R.drawable.test, R.raw.test)
        hashMapbestwords["opinion"] = Triple("nuomonė", R.drawable.opinion, R.raw.opinion)
        hashMapbestwords["league"] = Triple("lyga", R.drawable.league, R.raw.league)
        hashMapbestwords["with caution"] = Triple("atsargiai", R.drawable.caution, R.raw.withcaution)
        hashMapbestwords["often"] = Triple("dažnai", R.drawable.often, R.raw.often)
        hashMapbestwords["size"] = Triple("dydis", R.drawable.size, R.raw.size)
        hashMapbestwords["naturally"] = Triple("natūraliai", R.drawable.naturally, R.raw.naturally)
        hashMapbestwords["authority"] = Triple("autoritetas", R.drawable.authority, R.raw.authority)
        hashMapbestwords["Help"] = Triple("Pagalba", R.drawable.help, R.raw.help)
        hashMapbestwords["payment"] = Triple("mokėjimas", R.drawable.payment, R.raw.payment)
        hashMapbestwords["concrete"] = Triple("betonas", R.drawable.concrete, R.raw.concrete)
        hashMapbestwords["birth"] = Triple("gimimas", R.drawable.born1, R.raw.birth)
        hashMapbestwords["on the other hand"] = Triple("iš kitos pusės", R.drawable.emptyimage, R.raw.ontheotherhand)
        hashMapbestwords["question"] = Triple("klausimas", R.drawable.question, R.raw.question1)
        hashMapbestwords["space"] = Triple("kosmosas", R.drawable.space, R.raw.space1)
        hashMapbestwords["fast"] = Triple("greitai", R.drawable.fast, R.raw.fast)
        hashMapbestwords["part"] = Triple("dalis", R.drawable.part1, R.raw.part)
        hashMapbestwords["Every day"] = Triple("kasdien", R.drawable.emptyimage, R.raw.everyday)
        hashMapbestwords["there is no point"] = Triple("nėra prasmės", R.drawable.emptyimage, R.raw.thereisnopoint)
        hashMapbestwords["company"] = Triple("kompanija", R.drawable.company, R.raw.company)
        hashMapbestwords["actual"] = Triple("faktinis", R.drawable.actual, R.raw.actual)
        hashMapbestwords["easily"] = Triple("lengvai", R.drawable.easily, R.raw.easily)
        hashMapbestwords["heat"] = Triple("karštis", R.drawable.heat, R.raw.heat)
        hashMapbestwords["Food"] = Triple("Maistas", R.drawable.food, R.raw.food)
        hashMapbestwords["journey"] = Triple("kelionė", R.drawable.journey1, R.raw.journey)
        hashMapbestwords["Be quiet"] = Triple("Būti tyliam", R.drawable.bequiet, R.raw.bequiet)
        hashMapbestwords["accidentally"] = Triple("netyčia", R.drawable.byaccident, R.raw.accidentally)
        hashMapbestwords["Proposal"] = Triple("Pasiūlymas", R.drawable.proposal, R.raw.proposal)

    }
}