package com.example.visuallithuanian.constants

import com.example.visuallithuanian.R

object BusinessLanguageSingleton {

    val hashMapBusiness = HashMap<String,Triple<String,Int,Int>>()

    init {
        hashMapBusiness["work"] = Triple("darbas", R.drawable.work,R.raw.work)
        hashMapBusiness["account"] = Triple("sąskaita", R.drawable.account,R.raw.account)
        hashMapBusiness["brand"] = Triple("prekės ženklas", R.drawable.brand,R.raw.brand)
        hashMapBusiness["committee"] = Triple("komitetas", R.drawable.committee1,R.raw.committee)
        hashMapBusiness["project"] = Triple("projektas", R.drawable.project,R.raw.project)
        hashMapBusiness["guidelines"] = Triple("gaires", R.drawable.guidelines,R.raw.guidelines)
        hashMapBusiness["agreement"] = Triple("susitarimas", R.drawable.agreement11,R.raw.agreement)
        hashMapBusiness["office"] = Triple("biuras", R.drawable.office,R.raw.office)
        hashMapBusiness["Public Relations"] = Triple("viešieji ryšiai", R.drawable.publicrelations,R.raw.publicrelations)
        hashMapBusiness["product delivery"] = Triple("produkto pristatymas", R.drawable.productdelivery,R.raw.productdelivery)
        hashMapBusiness["wage"] = Triple("darbo užmokestis", R.drawable.wage,R.raw.wage)
        hashMapBusiness["to the consumer"] = Triple("vartotojui", R.drawable.toconsumer,R.raw.totheconsumer)
        hashMapBusiness["boss"] = Triple("bosas", R.drawable.boss,R.raw.boss)
        hashMapBusiness["to complain"] = Triple("pasiskųsti", R.drawable.complain,R.raw.tocomplain)
        hashMapBusiness["costs"] = Triple("išlaidos", R.drawable.cost,R.raw.costs)
        hashMapBusiness["meeting"] = Triple("susitikimas", R.drawable.meeting1,R.raw.meeting)
        hashMapBusiness["manager"] = Triple("vadybininkas", R.drawable.manager11,R.raw.manager)
        hashMapBusiness["to develop"] = Triple("vystytis", R.drawable.todevelop,R.raw.todevelop)
        hashMapBusiness["digital marketing"] = Triple("skaitmeninė rinkodara", R.drawable.digitalmarketing,R.raw.digitalmarketing)
        hashMapBusiness["distribution"] = Triple("paskirstymas", R.drawable.distribution,R.raw.distribution)
        hashMapBusiness["quantity"] = Triple("kiekis", R.drawable.quantity,R.raw.quantity)
        hashMapBusiness["public image"] = Triple("visuomenės įvaizdis", R.drawable.publicimage,R.raw.publicimage)
        hashMapBusiness["Market Research"] = Triple("rinkos tyrimai", R.drawable.marketresearch,R.raw.marketresearch)
        hashMapBusiness["profitable"] = Triple("pelningas", R.drawable.profitable,R.raw.profitable)
        hashMapBusiness["packaging"] = Triple("pakuotės", R.drawable.packaging,R.raw.packaging)
        hashMapBusiness["sponsor"] = Triple("rėmėjas", R.drawable.sponsor,R.raw.sponsor)
        hashMapBusiness["of the whole product"] = Triple("viso produkto", R.drawable.wholeproduct1,R.raw.ofthewholeproduct)
        hashMapBusiness["accounting"] = Triple("buhalterija", R.drawable.accounting,R.raw.accouting)
        hashMapBusiness["warranty"] = Triple("garantija", R.drawable.warranty,R.raw.warranty)
        hashMapBusiness["agenda"] = Triple("darbotvarkę", R.drawable.agenda,R.raw.agenda)
        hashMapBusiness["worker"] = Triple("darbuotojas", R.drawable.worker11,R.raw.worker)
        hashMapBusiness["advertising"] = Triple("reklama", R.drawable.advertising,R.raw.advertising)
        hashMapBusiness["publicity"] = Triple("viešumas", R.drawable.publicity1,R.raw.publicity)
        hashMapBusiness["consultant"] = Triple("konsultantas", R.drawable.consultant,R.raw.consultant)
        hashMapBusiness["video conferencing"] = Triple("vaizdo konferencija", R.drawable.videoconferencing,R.raw.videoconferencing)
        hashMapBusiness["condition"] = Triple("sąlyga", R.drawable.condition,R.raw.condition)
        hashMapBusiness["Analysis"] = Triple("analizė", R.drawable.analysis,R.raw.analysis)
        hashMapBusiness["effort"] = Triple("pastanga", R.drawable.effort,R.raw.effort)
        hashMapBusiness["consensus"] = Triple("sutarimas", R.drawable.consensus,R.raw.consensus)
        hashMapBusiness["strategy"] = Triple("strategija", R.drawable.strategy,R.raw.strategy)
        hashMapBusiness["temporary"] = Triple("laikinas", R.drawable.temporary,R.raw.temporary)
        hashMapBusiness["staff"] = Triple("personalas", R.drawable.staff,R.raw.staff)
        hashMapBusiness["headquarters"] = Triple("būstinė", R.drawable.headquarters,R.raw.headquarters)
        hashMapBusiness["commercial"] = Triple("komercinis", R.drawable.commercial,R.raw.commercial)
        hashMapBusiness["firm"] = Triple("įmonė", R.drawable.firm1,R.raw.firm)
        hashMapBusiness["factory"] = Triple("gamykla", R.drawable.factory,R.raw.factory)
        hashMapBusiness["to cooperate"] = Triple("bendradarbiauti", R.drawable.tocooperate,R.raw.tocoperate)
        hashMapBusiness["wholesaler"] = Triple("didmenininkas", R.drawable.wholesaler,R.raw.wholesaler)
        hashMapBusiness["inflation"] = Triple("infliacija", R.drawable.inflation,R.raw.inflation)
        hashMapBusiness["profit"] = Triple("pelnas", R.drawable.profit,R.raw.profit)
        hashMapBusiness["merger"] = Triple("susijungimas", R.drawable.merger,R.raw.merger)
        hashMapBusiness["Product"] = Triple("produktas", R.drawable.prodcut,R.raw.prodcut)
        hashMapBusiness["investor"] = Triple("investuotojas", R.drawable.investor,R.raw.inverstor)
        hashMapBusiness["risk"] = Triple("rizika", R.drawable.risk,R.raw.risk)
        hashMapBusiness["remuneration"] = Triple("atlygis", R.drawable.remuneration,R.raw.renumeration)
        hashMapBusiness["employee of the month"] = Triple("mėnesio darbuotojas", R.drawable.employeeofthemonth,R.raw.employeeofthemonth)
        hashMapBusiness["charity"] = Triple("labdara", R.drawable.charity,R.raw.charity)
        hashMapBusiness["deficiency"] = Triple("trūkumas", R.drawable.deficiency,R.raw.efficiency)
        hashMapBusiness["delivery"] = Triple("pristatymas", R.drawable.delivery,R.raw.delivery)
        hashMapBusiness["salary"] = Triple("atlyginimas", R.drawable.salary,R.raw.salary)
    }
}